### ISSUE TITLE
As a maintenance administrator, I should be able to login with access to the management program 

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#1]
**Description:**
The program requires an admin login to access admin functionality. The login screen will prompt for a username and a password, and will check for valid input.

**Task:**
- [ ] Connects to database.
- [ ] Reads from database with usernames
- [ ] Reads from database with passwords
- [ ] Text entry for username with label
- [ ] Text entry for password with label
- [ ] Failed text displays when invalid username or password
- [ ] [ Login ] button to attempt login
- [ ] [ Clear] button to remove login text

**Testing:**
- [ ] Attempt with empty username and/or password
- [ ] Attempt with empty incorrect username/password
- [ ] Attempt with a random string to check database works

**Definition of Done**
Be able to login as an admin using correct username and password, and be redirected to the admin page.

**Story points: 1**
