### ISSUE TITLE
As a maintenance administrator, I should be able to add a new stadium and its corresponding souvenirs

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#10]
**Description:**
Maintenance (administrator only) is only able to add a new stadium and its corresponding souvenirs by having your program read from an input file given to the class. It provides the capability to change the prices of the traditional souvenirs. Provide the capability to add new traditional souvenirs.

**Task:**
- [ ] tab containing all stadium's
- [ ] two table views side by side
- [ ] first table view contains all stadiums
- [ ] second table view contains all souvenirs
- [ ] souvenirs are shown based on the stadium that is clicked on
- [ ] section to put the information of a new stadium to be added
- [ ] button to add the stadium 
- [ ] the second button to cancel adding stadium

**Testing:**
- [ ] Go through each scenario to make sure there are no errors. 
- [ ] Be able to add new stadiums that don't exist. 
- [ ] Make sure all souvenirs match the corresponding stadium. 
- [ ] All stadiums must exist in the database and have all souvenirs.    

**Definition of Done**
Once fully complete, there should be a table view with all stadiums and corresponding souvenirs. You should be able to add new stadiums to the database and add corresponding souvenirs.   

**Points**
7
