### ISSUE TITLE
As a maintenance administrator, I should be able to upload new MLB information into the databse via an XSLX file.

### ISSUE THREAD

**Issue by rizzi-trevor** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#12]
**Description**:
An administrator should be able to add new MLB teams that will be available for users to incorporate into their trip plans. They will load the new teams into the database from the provided input file.

**Task:**
- Adding a team
   - [ ] Tab to display all team info
   - [ ] [Add] button to add new teams. 
   - [ ] Read input file and data
   - [ ] Checks for preexisting teams to make sure nothing duplicates.
   - [ ] Upload data to the SQL database.
   - [ ] confirm page to make sure you wanna make the changes.
   - [ ] confirm page contains yes or no buttons corresponding to functions to accept or reject the 
          request.
   - [ ] Display confirmation menu

**Testing**:
- Adding new teams
   - [ ] Read file into DB
   - [ ] Ensure valid input file
   - [ ] Prevent adding duplicate teams
   - [ ] Confirm successful addition of new items to DB
   - [ ] Prevent adding invalid objects 

**Definition of Done**
When enacted, maintenance admins will be able to select an option to add new teams and their corresponding data to be added to the DB. The program will read from an xslx file and add any teams not already in the DB to the DB. 

**Story points: 4**
