### ISSUE TITLE
As a maintenance administrator, I should be able to display certain MLB teams sorted by their team name or stadium name

### ISSUE THREAD

**Issue by rizzi-trevor** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#13]
**Description**:
An administrator should be able to display all of the baseball teams and their stadium names ordered A-Z by either the team name or the stadium name. The display will be ordered alphabetically for either selection.

**Task:**
- Display by team name
   - [ ] Tab containing teams
   - [ ] Button to display by team name
   - [ ] Display the teams in alphabetical order
- Display by stadium names
   - [ ] Tab containing teams
   - [ ] Button to display by stadium name
   - [ ] Display the stadium names in alphabetical order

**Testing**:
- Displaying by team name
   - [ ] Ensure valid data
   - [ ] Ensure they are displayed in correct order
   - [ ] Correct update to the display table

**Definition of Done**
When enacted, maintenance admins will be able to select if they want to display in order by team name or stadium name. When either is selected, the display table will update to show alphabetically either option. In both cases, the team name and corresponding stadium name will be displayed.

**Story points: 6**
