### ISSUE TITLE
As a maintenance administrator, I should be able to sort the MLB teams by their corresponding league (American or National))

### ISSUE THREAD

**Issue by rizzi-trevor** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#14]
**Description**:
An administrator should be able to select if they want to display the teams by american or national league. 

**Task:**
- Displaying by league
   - [ ] Button to display american league teams
   - [ ] Button to display national league teams
   - [ ] Display the american/national league teams by team name/ stadium name
   - [ ] Display all the corresponding team info

**Testing**:
- Displaying by league
   - [x] make sure all of the teams are in the correct league
   - [x] ensure correct updates of the display table
   - [x] Display only unique teams / prevent duplicates

**Definition of Done**
When enacted, maintenance admins will be able to select a display option to show either the national league teams or the american league teams. This will update their display table, showing the teams and their corresponding information in order for each league.

**Story points: 5**
