### ISSUE TITLE
As a maintenance administrator, I should be able to view the stock souvenirs listed for each MLB team

### ISSUE THREAD

**Issue by rizzi-trevor** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#15]
**Description**:
An administrator should be able to view the base 5 souvenirs that each ballpark sells.

**Task:**
-Adding souvenirs to database
   - Each team gets the same 5 starting souvenirs: cap, hat, pennant, jersey, ball
- Displaying souvenirs
  - [ ] Tab to display the complete list of souvenirs for each team
  - [ ] Display all the corresponding team info, including the 5 original souvenirs

**Testing**:
- Displaying by league
   - [ ] make sure all of the teams display the correct souvenirs
   - [ ] ensure correct updates of the display table
   - [ ] Display only unique teams / prevent duplicates

**Definition of Done**
When enacted, maintenance admins will be able to select a display option to show the souvenirs at for each baseball team. This will update their display table, showing the teams and their corresponding information.
**Story points: 5**
