### ISSUE TITLE
As a consumer, I should be able to display all relevant information related to any specific baseball team

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#2]
**Description**:
An consumer should be able to select a specific baseball team that exists, and the program will display all relevant information pertaining to that team. This information includes: Stadium name, seating capacity, location, playing surface, team name, league, date opened, distance to center field, ballpark typology, and roof type.

**Task:**
- Display info
   - [ ] Dropdown containing all the teams.
   - [ ] Option to select a team. 
   - [ ] Get the data related to that team from the database
   - [ ] Send the data to the GUI 
   - [ ] Refresh GUI to display all of this teams data clearly and legibly. 

**Testing**:
- Display info
   - [ ] Check to make sure dropdown with teams is correct
   - [ ] Ensure info displayed is correct for each team
   - [ ] Make sure NO other team's info is displayed

**Definition of Done**
When enacted, any customer will be able to select a baseball team from a dropdown menu, and they will be greeted with all of the relevant information to that team. This will be displayed clearly in a clean and legible GUI.

**Story points: 3**
