### ISSUE TITLE
As a baseball fan and consumer, I should be able to plan my DREAM vacation to the baseball parks

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#3]
**Description**:
A baseball fan/consumer should be able to choose a starting team and any other team that they would like to visit. The selections will be calculated to follow the shortest path. The total distance of the trip will also be displayed

**Task:**
- Creating a dream vacation
   - [ ] Ability to open page that user can plan their vacation on 
   - [ ] List of all the possible baseball teams 
   - [ ] Checkboxes for each team name and location so the user can select them
   - [ ] Dropdown to designate the starting team for the trip
   - [ ] Get all of the selected teams and calculate the shortest paths for the trip
   - [ ] Display the finalized trip to the user
   - [ ] Display the total distance of the trip to the user
   - [x] confirm page contains yes or no buttons corresponding to functions to accept or reject the 
          request.
   - [x] Display confirmation menu

**Testing**:
- Creating a trip/ vacation
   - [ ] Ensure all the teams are correct
   - [ ] Ensure the user can select as many teams as they would like
   - [ ] Make sure the trip algorithm is returning the correct result each time
   - [ ] Confirm the completed trip with
   - [ ] Check the distance of the trip

**Definition of Done**
When enacted, baseball fans and consumers will be able to plan their dream vacation where they can select any number of baseball teams for their trip. They will be able to specify the starting team, and can check off as many other teams as they like. The most efficient trip will be calculated and shown to the user. The distance of that trip will also be made clear to the user.

**Story points: 6**
