### ISSUE TITLE
As a maintenance administrator, I should be able to add new baseball teams and their information

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#4]
**Description**:
An administrator should be able to add new baseball teams and their corresponding information to the database / map with the click of a button. An input file will be read that uploads this data to the database.

**Task:**
- Adding new teams and souvenirs from input file 
   - [ ] [Add] button to add new teams from a file
   - [ ] Open input file
   - [ ] Read input file into database
   - [ ] Read input file and data
   - [ ] Checks for preexisting teams to make sure nothing duplicates.
   - [ ] Upload data to the SQL database.
   - [ ] confirm page to make sure you wanna make the changes.
   - [ ] confirm page contains yes or no buttons corresponding to functions to accept or reject the 
          request.
   - [ ] Display confirmation menu

**Testing**:
- Adding new teams/souvenirs from file
   - [ ] Read file into DB
   - [ ] Ensure valid input file
   - [ ] Prevent adding duplicate teams
   - [ ] Confirm successful addition of new items to DB
   - [ ] Prevent adding invalid objects 

**Definition of Done**
When enacted, maintenance admins will be able to add new teams and their corresponding information to the DB. The program will read from an input file and add any teams not already in the DB to the DB. 

**Story points: 4**
