### ISSUE TITLE
As a maintenance administrator, I should have the ability to modify stadium information

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#5]
**Description:**
Provide the ability to modify stadium information including capacity, stadium name, playing surface, roof type, ballpark, typology, date opened, distance to center field, and location if a team moves into a new stadium. (administrator only) (The Oakland Athletics are planning to move to the Oakland Ballpark with a seating capacity of 35,000 in 2023). 

**Task:**
- [ ] tab for the stadium information
- [ ] table view showing stadium information
- [ ] on the same tab a place for information for edit
- [ ] two buttons at the button of the page
- [ ] the first button for canceling the request
- [ ] a second button for updating the information
- [ ] information is edited through a line edit

**Testing:**
- [ ] Go through each stadium information to make sure it matches the database
- [ ] update stadium information and make sure that it is being directly updated inside the database. 
- [ ] Make sure errors are being caught by the program. 

**Definition of Done**
You are able to display all stadium information and update it on the spot directly through the program and update the database. 

**Points**
7
