### ISSUE TITLE
As a baseball fan, I should be able to purchase multiple souvenirs at each stadium

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#6]
**Description:**
At each stadium included in the trip, a fan should be able to purchase multiple souvenirs. The souvenir options should display the name and price, along with the chosen quantity and calculated totals. The souvenirs displayed should reflect any additions, removals, or changes to the souvenirs.

**Task:**
- [ ] Display a list of the souvenirs for the given stadium
- [ ] Allow the fan to choose whichever souvenirs they would like
- [ ] Allow the fan to specify a quantity to purchase
- [ ] Display the running totals for the selected souvenirs

**Testing:**
- [ ] Test for changes to the list of souvenirs
- [ ] Test for selecting different combinations of souvenirs
- [ ] Test large quantities and small quantities
- [ ] Test the total calculations
- [ ] Prevent invalid or negative inputs

**Definition of Done**
A fan should be able to select any combination and quantity of souvenirs per stadium, and should see a running total of their selections.

**Points**
8
