### ISSUE TITLE
As a baseball fan at the end of a trip, I should see a display of the total spent at each stadium and of the whole trip

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#7]
**Description:**
At the end of a trip, the program should display the total amount spent on souvenirs at each stadium, along with the grand total for all stadiums visited.

**Task:**
- [ ] Display the purchases from each stadium, including price, quantities, and totals
- [ ] Display the total for the entire trip

**Testing:**
- [ ] Compare the programs totals to the actual calculated totals

**Definition of Done**
The program should display accurate totals for the trip, at the end.

**Points**
5
