### ISSUE TITLE
As a baseball fan, I should be able to see a dispaly of all baseball teams or stadiums and their corresponding information, sorted by different values

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#8]
**Description:**
The program should display a list of all teams or stadiums, with specified information, sorted as listed below:

**Task:**
- [ ] Display the list of all the major league team names and their corresponding stadiums names sorted by team name.
- [ ] Display the list of all the major league team names and their corresponding stadiums names sorted by stadium name.
- [ ] Display the list of American League team names and their corresponding stadiums names sorted by team name.
- [ ] Display the list of National League team names and their corresponding stadiums names sorted by stadium name.
- [ ] Display the list of stadiums and their corresponding team name sorted by park typology.  Be sure to display park typology.
- [ ] Display the list of team names that have an open roof type sorted by team name.  Display the number of teams with an open roof type.
- [ ] Display the list of stadiums and their corresponding team name in chronological order (oldest to newest) using date opened.   Be sure to display date opened.

**Testing:**
- [ ] Test the display accurately lists all relevant items.
- [ ] Test the display updates with new stadiums and/or teams
- [ ] Test the display sorts correctly on the various values

**Definition of Done**
The program accurately displays updated lists meeting the above criteria.

**Points**
4
