### ISSUE TITLE
As a maintenance administrator, I should be able to add new or delete traditional souvenirs

### ISSUE THREAD

**Issue by NickReardon** [CS1DTeamRATS/CS1D---Project-2---Take-Me-Out-to-the-Ball-Game#9]
**Description:**
Maintenance (administrator only), provides the capability to change the prices of the traditional souvenirs and provide the capability to add new traditional souvenirs, and the capability to delete traditional souvenirs. 

**Task:**
- [ ] A table view displaying all the souvenirs
- [ ] line edits with souvenirs and prices
- [ ] buttons to allow you to commit the changes
- [ ] button to cancel the changes
- [ ] button to add souvenir 
- [ ] button to remove souvenir

**Testing:**
- [ ] Go through each souvenir and edit it and make sure that it catches all error checks. 
- [ ] Make sure that the database is getting the right information through the program. 

**Definition of Done**
Once complete I should be able to fully access all souvenirs through the program and be able to add or remove a souvenir without any duplications. 

**Points**
6
